default:
	R -e 'require(rmarkdown) ; render("analysis.Rmd",  output_format=pdf_document(toc=TRUE))'

repro:
	R -e 'require(rmarkdown) ; render("ReproducePaper.Rmd",  output_format=pdf_document(toc=TRUE))'

